baseURL = 'https://charl-potgieter.github.io/AustralianSchoolMaths/'
languageCode = 'en-us'
title = 'Australian school maths'
theme = 'hugo-book'

# https://gohugo.io/host-and-deploy/host-on-github-pages/
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true


[params]
SiteRoot = "AustralianSchoolMaths"
custom_css = ["assets/_custom.css"]
